"""Export one test sample (input vector + label) to test_sample.h.

Pairs with export_model.py — together they give you everything needed to
compile example_main.c and verify the C inference matches Keras on a single
known sample.

Usage:
    python3 export_sample.py mnist  test_sample.h            # 1st MNIST test image
    python3 export_sample.py mnist  test_sample.h --index 42 # the 43rd one
    python3 export_sample.py fmnist test_sample.h
    python3 export_sample.py cifar5 test_sample.h
    python3 export_sample.py har    test_sample.h
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

import keras  # noqa: E402


# -------------------------------------------------------------------------
# Dataset loaders — match the preprocessing in each *_neuroc_paper.py script
# -------------------------------------------------------------------------
def load_mnist(idx: int, center: bool = False):
    (_, _), (x, y) = keras.datasets.mnist.load_data()
    sample = x[idx].astype("float32") / 255.0
    if center:
        sample = sample - 0.5
    return sample.reshape(-1), int(y[idx])


def load_fmnist(idx: int, center: bool = False):
    (_, _), (x, y) = keras.datasets.fashion_mnist.load_data()
    sample = x[idx].astype("float32") / 255.0
    if center:
        sample = sample - 0.5
    return sample.reshape(-1), int(y[idx])


def load_cifar5(idx: int, center: bool = False):
    # `center` ignored for cifar5 — already mean/std standardized.
    (_, _), (x_all, y_all) = keras.datasets.cifar10.load_data()
    y_all = y_all.flatten()
    mask = y_all < 5
    x = x_all[mask]
    y = y_all[mask]

    # Same per-channel standardization as cifar5_neuroc_paper.py.
    mean = np.array([0.4914, 0.4822, 0.4465]) * 255
    std  = np.array([0.2470, 0.2435, 0.2616]) * 255
    sample = (x[idx].astype("float32") - mean) / std
    return sample.reshape(-1), int(y[idx])


def load_har(idx: int, center: bool = False):
    # `center` ignored for har — features already in [-1, 1].
    """Use the same har_data module the training scripts use.

    This guarantees the C inference sees exactly the same input the training
    pipeline produced — no risk of preprocessing mismatch (different URL,
    different normalization, off-by-one label shift, etc.).
    """
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "har_comparison"))
    from har_data import load_har as _load_har    # noqa: E402
    x_train, y_train, x_test, y_test = _load_har()
    return x_test[idx].astype("float32"), int(y_test[idx])


def load_kws(idx: int, center: bool = False):
    # `center` ignored for kws — MFCCs already standardized per feature.
    """Use the same kws_data module the training scripts use.

    Same rationale as load_har: avoid any chance of preprocessing drift
    between Python training and C inference verification.
    """
    import sys
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "kws_comparison"))
    from kws_data import load_kws as _load_kws    # noqa: E402
    x_train, y_train, x_test, y_test = _load_kws()
    return x_test[idx].astype("float32"), int(y_test[idx])


LOADERS = {
    "mnist":  load_mnist,
    "fmnist": load_fmnist,
    "cifar5": load_cifar5,
    "har":    load_har,
    "kws":    load_kws,
}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("dataset", choices=sorted(LOADERS.keys()))
    ap.add_argument("header_path")
    ap.add_argument("--index", type=int, default=0,
                    help="Which test-set sample to export (default: 0)")
    ap.add_argument("--center", action="store_true",
                    help="Subtract 0.5 after /255 (TNN training preprocessing for mnist/fmnist)")
    args = ap.parse_args()

    sample, label = LOADERS[args.dataset](args.index, center=args.center)
    sample = np.asarray(sample, dtype=np.float32).ravel()

    lines: list[str] = []
    lines.append("/* AUTO-GENERATED by c_port/export_sample.py — do not edit. */")
    lines.append("")
    lines.append("#ifndef NEUROC_TEST_SAMPLE_H")
    lines.append("#define NEUROC_TEST_SAMPLE_H")
    lines.append("")
    lines.append(f"/* Dataset: {args.dataset}   sample index: {args.index} */")
    lines.append(f"#define TEST_INPUT_SIZE {sample.size}")
    lines.append(f"#define TEST_LABEL      {label}")
    lines.append("")
    lines.append(f"static const float TEST_INPUT[{sample.size}] = {{")
    chunk: list[str] = []
    for i, v in enumerate(sample):
        chunk.append("%a" % float(v))
        if (i + 1) % 8 == 0:
            lines.append("    " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("    " + ", ".join(chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* NEUROC_TEST_SAMPLE_H */")

    out = Path(args.header_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    size_kb = out.stat().st_size / 1024.0
    print(f"Wrote {out}  ({size_kb:.1f} KB)   label={label}")


if __name__ == "__main__":
    main()
