"""Export a trained TNN (.keras) to model_data.h for the same C engine.

Mathematically: TNN forward = NeuroC forward with scale[j] = 1.0 for all j.
So we re-use the existing block-based ternary engine (neuroc.c) and just
emit a layer where every per-neuron scale is 1.0.

Usage:
    python3 export_tnn.py <trained_tnn.keras> <output_header.h>
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np


HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
# Re-use the NeuroC array-emit / activation-mapping helpers from export_model.py
from export_model import _emit_array, _activation_name  # noqa: E402

import keras  # noqa: E402
import tensorflow as tf  # noqa: E402


# Re-define the training-time TNNLayer + helpers locally so Keras can
# deserialize a TNN .keras archive that was saved using these classes.
def ternary_quantize(latent):
    threshold = 0.5 * tf.reduce_mean(tf.abs(latent))
    q = tf.zeros_like(latent)
    q = tf.where(latent >  threshold,  tf.ones_like(latent), q)
    q = tf.where(latent < -threshold, -tf.ones_like(latent), q)
    latent_clipped = tf.clip_by_value(latent, -1.0, 1.0)
    return tf.stop_gradient(q - latent_clipped) + latent_clipped


class WeightClip(keras.constraints.Constraint):
    def __init__(self, clip_value=1.0):
        self.clip_value = clip_value
    def __call__(self, w):
        return tf.clip_by_value(w, -self.clip_value, self.clip_value)
    def get_config(self):
        return {"clip_value": self.clip_value}


class TNNLayer(keras.layers.Layer):
    """Mirror of the training-time TNNLayer used in *_tnn_*.py files.
    No per-neuron scale — pure ternary.
    """
    def __init__(self, units, activation=None, **kwargs):
        super().__init__(**kwargs)
        self.units = units
        self.activation = keras.activations.get(activation)

    def build(self, input_shape):
        in_dim = int(input_shape[-1])
        self.latent_kernel = self.add_weight(
            name="latent_kernel", shape=(in_dim, self.units),
            initializer="glorot_uniform",
            constraint=WeightClip(1.0),
            trainable=True,
        )
        self.bias = self.add_weight(
            name="bias", shape=(self.units,),
            initializer="zeros", trainable=True,
        )

    def call(self, x):
        A = ternary_quantize(self.latent_kernel)
        z = tf.matmul(x, A) + self.bias
        return self.activation(z)

    def get_config(self):
        cfg = super().get_config()
        cfg.update({
            "units": self.units,
            "activation": keras.activations.serialize(self.activation),
        })
        return cfg


def export_tnn(model_path: str, header_path: str) -> None:
    print(f"Loading {model_path} ...")
    model = keras.models.load_model(
        model_path,
        custom_objects={
            "TNNLayer": TNNLayer,
            "WeightClip": WeightClip,
            "ternary_quantize": ternary_quantize,
        },
        compile=False,
    )

    tnn_layers = [l for l in model.layers if isinstance(l, TNNLayer)]
    if not tnn_layers:
        raise RuntimeError("Model contains no TNNLayer instances.")

    max_width = max(int(l.units) for l in tnn_layers)
    input_size = int(tnn_layers[0].latent_kernel.shape[0])
    output_size = int(tnn_layers[-1].units)

    lines = []
    lines.append("/* AUTO-GENERATED by c_port/export_tnn.py — do not edit. */")
    lines.append("/* TNN exported as Neuro-C with per-neuron scale = 1.0       */")
    lines.append("")
    lines.append("#ifndef NEUROC_MODEL_DATA_H")
    lines.append("#define NEUROC_MODEL_DATA_H")
    lines.append("")
    lines.append('#include "neuroc.h"')
    lines.append("")
    lines.append(f"#define MODEL_INPUT_SIZE       {input_size}")
    lines.append(f"#define MODEL_OUTPUT_SIZE      {output_size}")
    lines.append(f"#define MODEL_MAX_LAYER_WIDTH  {max_width}")
    lines.append("")

    BLOCK_SIZE = 256
    layer_struct_inits = []

    for i, layer in enumerate(tnn_layers):
        kernel = ternary_quantize(layer.latent_kernel).numpy()
        bias   = layer.bias.numpy().astype(np.float32)
        in_dim, units = kernel.shape

        # TNN has no scale — emit constant 1.0 per output neuron.
        scale = np.ones(units, dtype=np.float32)

        num_blocks = (in_dim + BLOCK_SIZE - 1) // BLOCK_SIZE

        pos_col_ptr_all, neg_col_ptr_all = [], []
        pos_indices_all, neg_indices_all = [], []
        pos_block_offset, neg_block_offset = [0], [0]

        for b in range(num_blocks):
            block_start = b * BLOCK_SIZE
            block_end   = min(block_start + BLOCK_SIZE, in_dim)
            block       = kernel[block_start:block_end, :]

            block_pos_cp, block_neg_cp = [0], [0]
            block_pos_idx, block_neg_idx = [], []
            for j in range(units):
                col = block[:, j]
                p = np.flatnonzero(col > 0).tolist()
                n = np.flatnonzero(col < 0).tolist()
                block_pos_idx.extend(p)
                block_neg_idx.extend(n)
                block_pos_cp.append(len(block_pos_idx))
                block_neg_cp.append(len(block_neg_idx))

            pos_col_ptr_all.extend(block_pos_cp)
            neg_col_ptr_all.extend(block_neg_cp)
            pos_indices_all.extend(block_pos_idx)
            neg_indices_all.extend(block_neg_idx)
            pos_block_offset.append(len(pos_indices_all))
            neg_block_offset.append(len(neg_indices_all))

        n_pos = len(pos_indices_all)
        n_neg = len(neg_indices_all)
        n_total = in_dim * units
        n_zero = n_total - n_pos - n_neg
        act_serialized = keras.activations.serialize(layer.activation)
        print(f"  Layer {i:>2}  {in_dim:>5} -> {units:<5}  "
              f"blocks={num_blocks}  +1={n_pos:>7,}  -1={n_neg:>7,}  "
              f"0={n_zero:>7,} ({n_zero/n_total:.1%})  act={act_serialized}")

        lines.append(f"/* ---- Layer {i}: {in_dim} -> {units}, "
                     f"{num_blocks} blocks x {BLOCK_SIZE}, {act_serialized} ---- */")
        lines.append(_emit_array(f"L{i}_pos_col_ptr",      "uint16_t", pos_col_ptr_all))
        lines.append(_emit_array(f"L{i}_pos_block_offset", "uint32_t", pos_block_offset))
        lines.append(_emit_array(f"L{i}_pos_indices",      "uint8_t",  pos_indices_all))
        lines.append(_emit_array(f"L{i}_neg_col_ptr",      "uint16_t", neg_col_ptr_all))
        lines.append(_emit_array(f"L{i}_neg_block_offset", "uint32_t", neg_block_offset))
        lines.append(_emit_array(f"L{i}_neg_indices",      "uint8_t",  neg_indices_all))
        lines.append(_emit_array(f"L{i}_scale", "float", scale.tolist()))
        lines.append(_emit_array(f"L{i}_bias",  "float", bias.tolist()))
        lines.append("")

        layer_struct_inits.append(
            "    {\n"
            f"        .input_size       = {in_dim},\n"
            f"        .output_size      = {units},\n"
            f"        .block_size       = {BLOCK_SIZE},\n"
            f"        .num_blocks       = {num_blocks},\n"
            f"        .pos_col_ptr      = L{i}_pos_col_ptr,\n"
            f"        .pos_block_offset = L{i}_pos_block_offset,\n"
            f"        .pos_indices      = L{i}_pos_indices,\n"
            f"        .neg_col_ptr      = L{i}_neg_col_ptr,\n"
            f"        .neg_block_offset = L{i}_neg_block_offset,\n"
            f"        .neg_indices      = L{i}_neg_indices,\n"
            f"        .scale            = L{i}_scale,\n"
            f"        .bias             = L{i}_bias,\n"
            f"        .activation       = {_activation_name(act_serialized)},\n"
            "    }"
        )

    lines.append("static const neuroc_layer_t MODEL_LAYERS[] = {")
    lines.append(",\n".join(layer_struct_inits))
    lines.append("};")
    lines.append("")
    lines.append("static const neuroc_model_t MODEL = {")
    lines.append(f"    .num_layers      = {len(tnn_layers)},")
    lines.append(f"    .max_layer_width = {max_width},")
    lines.append("    .layers          = MODEL_LAYERS,")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* NEUROC_MODEL_DATA_H */")

    out_path = Path(header_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    size_kb = out_path.stat().st_size / 1024.0
    print(f"Wrote {out_path}  ({size_kb:.1f} KB of C source)")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("model_path", help="Path to a trained TNN .keras model")
    ap.add_argument("header_path", help="Where to write the C header (model_data.h)")
    args = ap.parse_args()
    export_tnn(args.model_path, args.header_path)
