"""Export a trained Keras MLP to a C header consumable by mlp.c.

Usage:
    python3 export_mlp.py <trained_mlp.keras> <output_header.h>

Layout of the emitted header:

    static const float    L0_kernel[N0 * M0] = { ... };  // row-major
    static const float    L0_bias[M0]        = { ... };
    static const float    L1_kernel[N1 * M1] = { ... };
    static const float    L1_bias[M1]        = { ... };
    ...
    static const mlp_layer_t MLP_MODEL_LAYERS[] = { ... };
    static const mlp_model_t MLP_MODEL          = { ... };

    #define MLP_MODEL_INPUT_SIZE       N0
    #define MLP_MODEL_OUTPUT_SIZE      Mlast
    #define MLP_MODEL_MAX_LAYER_WIDTH  max(M0, M1, ...)
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import keras


# -------------------------------------------------------------------------
# Helpers
# -------------------------------------------------------------------------
def _emit_array(name: str, ctype: str, values, per_line: int = 8) -> str:
    lines = [f"static const {ctype} {name}[{len(values)}] = {{"]
    fmt = "%a" if ctype.startswith("float") else "%d"
    chunk = []
    for i, v in enumerate(values):
        chunk.append(fmt % v)
        if (i + 1) % per_line == 0:
            lines.append("    " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("    " + ", ".join(chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def _activation_name(act_serialized) -> str:
    if act_serialized in (None, "linear"):
        return "MLP_ACT_NONE"
    if act_serialized == "relu":
        return "MLP_ACT_RELU"
    if act_serialized == "softmax":
        return "MLP_ACT_SOFTMAX"
    raise ValueError(f"Unsupported activation for MLP C port: {act_serialized!r}")


# -------------------------------------------------------------------------
# Exporter
# -------------------------------------------------------------------------
def export_mlp(model_path: str, header_path: str) -> None:
    print(f"Loading {model_path} ...")
    model = keras.models.load_model(model_path, compile=False)

    dense_layers = [l for l in model.layers if isinstance(l, keras.layers.Dense)]
    if not dense_layers:
        raise RuntimeError("Model contains no Dense layers.")

    # Skip dropout / input layers; we only care about Dense.
    input_size = int(dense_layers[0].input.shape[-1])
    output_size = int(dense_layers[-1].units)
    max_width = max(int(l.units) for l in dense_layers)

    lines = []
    lines.append("/* AUTO-GENERATED by c_port/export_mlp.py — do not edit. */")
    lines.append("")
    lines.append("#ifndef MLP_MODEL_DATA_H")
    lines.append("#define MLP_MODEL_DATA_H")
    lines.append("")
    lines.append('#include "mlp.h"')
    lines.append("")
    lines.append(f"#define MLP_MODEL_INPUT_SIZE       {input_size}")
    lines.append(f"#define MLP_MODEL_OUTPUT_SIZE      {output_size}")
    lines.append(f"#define MLP_MODEL_MAX_LAYER_WIDTH  {max_width}")
    lines.append("")

    layer_struct_inits = []

    total_params = 0
    for i, layer in enumerate(dense_layers):
        # Keras Dense kernel shape: (input_dim, units), row-major as we want.
        kernel = layer.kernel.numpy().astype(np.float32)  # shape (N, M)
        bias   = layer.bias.numpy().astype(np.float32)
        N, M = kernel.shape
        total_params += N * M + M

        act_serialized = keras.activations.serialize(layer.activation)
        print(f"  Layer {i:>2}  {N:>5} -> {M:<5}  "
              f"params={N*M + M:>7,}  bytes={(N*M + M)*4:>9,}  act={act_serialized}")

        # Flatten kernel row-major (Keras Dense is already row-major: row i contains
        # all weights from input i to all outputs).
        flat_kernel = kernel.reshape(-1).tolist()

        lines.append(f"/* ---- Layer {i}: {N} -> {M}, {act_serialized} ---- */")
        lines.append(_emit_array(f"L{i}_kernel", "float", flat_kernel))
        lines.append(_emit_array(f"L{i}_bias",   "float", bias.tolist()))
        lines.append("")

        layer_struct_inits.append(
            "    {\n"
            f"        .input_size  = {N},\n"
            f"        .output_size = {M},\n"
            f"        .kernel      = L{i}_kernel,\n"
            f"        .bias        = L{i}_bias,\n"
            f"        .activation  = {_activation_name(act_serialized)},\n"
            "    }"
        )

    lines.append("static const mlp_layer_t MLP_MODEL_LAYERS[] = {")
    lines.append(",\n".join(layer_struct_inits))
    lines.append("};")
    lines.append("")
    lines.append("static const mlp_model_t MLP_MODEL = {")
    lines.append(f"    .num_layers      = {len(dense_layers)},")
    lines.append(f"    .max_layer_width = {max_width},")
    lines.append("    .layers          = MLP_MODEL_LAYERS,")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* MLP_MODEL_DATA_H */")

    out_path = Path(header_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")

    size_kb = out_path.stat().st_size / 1024.0
    weight_bytes = total_params * 4
    print(f"\nTotal parameters    : {total_params:,}")
    print(f"Weights at float32  : {weight_bytes:,} bytes ({weight_bytes/1024:.1f} KB)")
    print(f"Wrote {out_path}  ({size_kb:.1f} KB of C source)")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("model_path", help="Path to a trained .keras MLP model")
    ap.add_argument("header_path", help="Where to write the C header (e.g. mlp_data.h)")
    args = ap.parse_args()
    export_mlp(args.model_path, args.header_path)
