/* main_mspm0.c — float Neuro-C inference timer for MSPM0G3507.
 * Uses SysTick (24-bit downcounter) for cycle measurement; M0+ lacks DWT. */

#include <stdio.h>
#include <stdint.h>
#include <ti/devices/msp/msp.h>

#include "neuroc.h"
#include "model_data.h"
#include "test_sample.h"


/* Statically allocated activation buffers — no heap. */
static float scratch_a[MODEL_MAX_LAYER_WIDTH];
static float scratch_b[MODEL_MAX_LAYER_WIDTH];
static float model_out[MODEL_OUTPUT_SIZE];


/* SysTick free-running cycle counter setup. */
static void systick_cycle_counter_init(void) {
    SysTick->LOAD = 0x00FFFFFFul;           /* 24-bit max reload */
    SysTick->VAL  = 0;                       /* clear current value */
    SysTick->CTRL = SysTick_CTRL_CLKSOURCE_Msk   /* CPU clock */
                  | SysTick_CTRL_ENABLE_Msk;     /* enable, no interrupt */
}

/* Read 24-bit downcounter as up-counting cycles since reset. */
static inline uint32_t systick_read_cycles(void) {
    /* SysTick counts DOWN, so cycles-since-start = LOAD - VAL.
     * Use only low 24 bits because LOAD is 24-bit. */
    return (SysTick->LOAD - SysTick->VAL) & 0x00FFFFFFul;
}


int main(void) {
    /* SysConfig (auto-generated by CCS) usually handles SYSCTL init for the
     * MSPM0G3507. If you used the empty template without SysConfig, the
     * MCU boots to its default SYSOSC clock (~32 MHz on MSPM0G350x) which
     * is fine for cycle-count measurements — cycles are clock-independent. */

    systick_cycle_counter_init();

    printf("=== Neuro-C inference on MSPM0G3507 (Cortex-M0+) ===\n");
    printf("Model: input %u  output %u  layers %u  max_width %u\n",
           (unsigned)MODEL_INPUT_SIZE,
           (unsigned)MODEL_OUTPUT_SIZE,
           (unsigned)MODEL.num_layers,
           (unsigned)MODEL_MAX_LAYER_WIDTH);

    /* Time one inference. Reset SysTick right before so we know we start
     * from 0xFFFFFF and won't wrap mid-measurement. */
    SysTick->VAL = 0;
    uint32_t t0 = systick_read_cycles();          /* should be ~0 */
    neuroc_forward(&MODEL, TEST_INPUT, model_out, scratch_a, scratch_b);
    uint32_t t1 = systick_read_cycles();
    uint32_t cycles = (t1 - t0) & 0x00FFFFFFul;

    int predicted = neuroc_argmax(model_out, MODEL_OUTPUT_SIZE);

    printf("\n--- Result ---\n");
    printf("Predicted : %d\n", predicted);
    printf("True      : %d\n", (int)TEST_LABEL);
    printf("Match     : %s\n", predicted == (int)TEST_LABEL ? "YES" : "NO");

    printf("\n--- Latency ---\n");
    printf("Cycles    : %lu\n", (unsigned long)cycles);
    printf("ms @ 32 MHz default : %.3f\n", cycles / 32000.0);
    printf("ms @ 80 MHz max     : %.3f\n", cycles / 80000.0);
    printf("ms @ 8 MHz (paper)  : %.3f\n", cycles / 8000.0);

    while (1) { __NOP(); }
    return 0;
}
